// Lock screen: wait-free countdown, balance, coin unlock charges once, shop.
import { sql as _sql } from "./lib.mjs";
_sql("update wallets set balance_coins = 100 where user_id = (select id from auth.users where email = 'reader1@test.mn')");
_sql("delete from unlocks where user_id = (select id from auth.users where email = 'reader1@test.mn')");
_sql("delete from wait_free_timers where user_id = (select id from auth.users where email = 'reader1@test.mn')");
_sql("delete from wallet_transactions where user_id = (select id from auth.users where email = 'reader1@test.mn')");
import { launch, assert, BASE } from "./lib.mjs";
const b = await launch(); const ctx = await b.newContext({ viewport: { width: 360, height: 800 }, storageState: "/tmp/zugaa-reader.json" }); const p = await ctx.newPage();
await p.goto(`${BASE}/s/arvan-guravdugaar-davhar/3`);
await p.waitForSelector("#locked-title"); await p.waitForTimeout(1500);
let main = await p.textContent("main");
assert(main.includes("Үнэгүй нээгдэх хүртэл"), "wait-free countdown shown");
assert(main.includes("Таны үлдэгдэл: 100 coin"), "balance shown on lock screen");
assert(/23 цаг 5\d мин|24 цаг/.test(main), "countdown text ~24h: " + /хүртэл: ([^Х]+)/.exec(main)?.[1]);
await p.click("text=40 coin-оор нээх");
await p.waitForSelector("footer");
main = await p.textContent("main");
assert(main.includes("Чи надгүйгээр явчихлаа"), "chapter fully opens after coin unlock");
await p.goto(`${BASE}/s/arvan-guravdugaar-davhar/4`);
await p.waitForSelector("#locked-title"); await p.waitForTimeout(1000);
main = await p.textContent("main");
assert(main.includes("Таны үлдэгдэл: 60 coin"), "charged exactly 40 once");
assert(main.includes("Үнэгүй хүлээх цаг") || main.includes("Үнэгүй нээгдэх хүртэл"), "wait-free state on next chapter");
await p.goto(`${BASE}/me`); await p.waitForSelector("#wallet");
main = await p.textContent("main");
assert(main.includes("60 coin") && main.includes("Уншсан түүх"), "Миний shows balance and history");
await p.goto(`${BASE}/shop?need=20`); await p.waitForSelector("#subs");
main = await p.textContent("main");
assert(main.includes("Сарын эрх") && main.includes("20,000₮") && main.includes("3,000₮"), "shop lists products with MNT prices");
assert(main.includes("20 coin дутуу"), "shop shows shortfall");
await b.close();
